### ISSUE TITLE
problem in altdns.py

### ISSUE THREAD

**Issue by shadihh9** [infosec-au/altdns#24]
when install  tools and dont display altdns.py i cant find it and when use commond dont work

**Comment by shadihh9** [comment]
i see this message Traceback (most recent call last):
  File "/usr/local/bin/altdns", line 6, in <module>
    from altdns.__main__ import main
  File "/usr/local/lib/python3.7/dist-packages/altdns/__main__.py", line 10, in <module>
    from Queue import Queue as Queue
ModuleNotFoundError: No module named 'Queue'

**Comment by phspade** [comment]
Do this

`python -m pip install py-altdns && export PATH=$PATH:~/.local/bin`

**Comment by shadihh9** [comment]
i do but the same problem

**Comment by shadihh9** [comment]
Traceback (most recent call last):
  File "/usr/local/bin/altdns", line 6, in <module>
    from altdns.__main__ import main
  File "/usr/local/lib/python3.7/dist-packages/altdns/__main__.py", line 10, in <module>
    from Queue import Queue as Queue
ModuleNotFoundError: No module named 'Queue'

**Comment by shadihh9** [comment]
after that

**Comment by shadihh9** [comment]
i think problem python 2.7 on kali linux

**Comment by harleo** [comment]
@shadihh9 and anyone running into the same problem, do this:

1. Goto /usr/local/lib/python3.7/site-packages/altdns/
2. Open `__main__.py`
3. Change `from Queue import Queue as Queue` to `from queue import Queue as Queue`

That should resolve it.

**Comment by m4xx101** [comment]
### After doing the changes in __main__.py file 

Change from ```Queue import Queue as Queue``` to from ```queue import Queue as Queue```

I got following issue (In windows running Python 3.7.4 )

```py
c:\users\91986\appdata\local\programs\python\python38\lib\site-packages\altdns\__main__.py:45: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if actual_sub[-1:] is not ".":
c:\users\91986\appdata\local\programs\python\python38\lib\site-packages\altdns\__main__.py:102: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if len(current_sub[0]) > 0 and actual_sub[:1] is not "-":
c:\users\91986\appdata\local\programs\python\python38\lib\site-packages\altdns\__main__.py:112: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if actual_sub[-1:] is not "-":
c:\users\91986\appdata\local\programs\python\python38\lib\site-packages\altdns\__main__.py:175: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if len(result) is 1:
usage: altdns [-h] -i INPUT -o OUTPUT [-w WORDLIST] [-r] [-n] [-e] [-d DNSSERVER] [-s SAVE] [-t THREADS]

optional arguments:
  -h, --help            show this help message and exit
  -i INPUT, --input INPUT
                        List of subdomains input
  -o OUTPUT, --output OUTPUT
                        Output location for altered subdomains
  -w WORDLIST, --wordlist WORDLIST
                        List of words to alter the subdomains with
  -r, --resolve         Resolve all altered subdomains
  -n, --add-number-suffix
                        Add number suffix to every domain (0-9)
  -e, --ignore-existing
                        Ignore existing domains in file
  -d DNSSERVER, --dnsserver DNSSERVER
                        IP address of resolver to use (overrides system default)
  -s SAVE, --save SAVE  File to save resolved altered subdomains to
  -t THREADS, --threads THREADS
                        Amount of threads to run simultaneously
```

**Comment by infosec-au** [comment]
I've merged in a PR that resolves this. Thanks for everyone's help here.

**Comment by sandman4812av** [comment]
++
replacing from queue import Queue as Queue to from multiprocessing import Queue in Pyton 3 (Kali) also works with this error

**Comment by shabbadont** [comment]
> I've merged in a PR that resolves this. Thanks for all the help here.

Doesn't work. Syntax error messages

**Comment by yahaya1002** [comment]
i dont why is show that when i try to run th software:
Traceback (most recent call last):
  File "/usr/bin/altdns", line 33, in <module>
    sys.exit(load_entry_point('py-altdns==1.0.2', 'console_scripts', 'altdns')())
  File "/usr/bin/altdns", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/yahaya/.local/lib/python3.10/site-packages/altdns/__main__.py", line 15, in <module>
    import tldextract
  File "/usr/lib/python3/dist-packages/tldextract/__init__.py", line 3, in <module>
    from .tldextract import extract, TLDExtract
  File "/usr/lib/python3/dist-packages/tldextract/tldextract.py", line 61, in <module>
    from .suffix_list import get_suffix_lists
  File "/usr/lib/python3/dist-packages/tldextract/suffix_list.py", line 7, in <module>
    import requests
  File "/home/yahaya/.local/lib/python3.10/site-packages/requests/__init__.py", line 64, in <module>
    from . import utils
  File "/home/yahaya/.local/lib/python3.10/site-packages/requests/utils.py", line 28, in <module>
    from .cookies import RequestsCookieJar, cookiejar_from_dict
  File "/home/yahaya/.local/lib/python3.10/site-packages/requests/cookies.py", line 164, in <module>
    class RequestsCookieJar(cookielib.CookieJar, collections.MutableMapping):
AttributeError: module 'collections' has no attribute 'MutableMapping'
