### ISSUE TITLE
No altdns.py

### ISSUE THREAD

**Issue by njob45** [infosec-au/altdns#28]
There is no altdns.py file. any solution for this

**Comment by CuriousIncident** [comment]
You normally install it via "pip install py-altdns", so you don't need an altdns.py file directly, if you want to install it through github run "python3 setup.py install".

**Comment by nature1995** [comment]
Usage:
```
# altdns -i subdomains.txt -o data_output -w words.txt -r -s results_output.txt
```

**Comment by hassankhan98** [comment]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/bin/altdns", line 5, in <module>
    from altdns.__main__ import main
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/altdns/__main__.py", line 10, in <module>
    from Queue import Queue as Queue
ModuleNotFoundError: No module named 'Queue'

**Comment by Te-droid** [comment]
It's python2.7. How did you install it?

**Comment by hruday007** [comment]
It works perfectly 💯 
```
import sys
is_py2 = sys.version[0] == '2'
if is_py2:
    import Queue as queue
else:
    import queue as queue

```
Python 3

change line 10 `from queue import Queue as queue`  and line 248 `q = queue()` in __main__.py file

**Comment by sammiie** [comment]
> It works perfectly 💯
> 
> ```
> import sys
> is_py2 = sys.version[0] == '2'
> if is_py2:
>     import Queue as queue
> else:
>     import queue as queue
> ```
> 
> Python 3
> 
> change line 10 `from queue import Queue as queue` and line 248 `q = queue()` in **main**.py file

please explain what to change and what to replace it with.
