### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by chawdamrunal** [infosec-au/altdns#35]
Traceback (most recent call last):
  File "/usr/local/bin/altdns", line 11, in <module>
    load_entry_point('py-altdns==1.0.0', 'console_scripts', 'altdns')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 490, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2854, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2445, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2451, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.8/dist-packages/altdns/__main__.py", line 10, in <module>
    from Queue import Queue as Queue
ModuleNotFoundError: No module named 'Queue'

**Comment by vknownothing** [comment]
#31 Here 👍
