### ISSUE TITLE
issue with threads

### ISSUE THREAD

**Issue by merlin303** [infosec-au/altdns#4]
I'm running this on an old laptop and am getting the following error

Traceback (most recent call last):
  File "./altdns.py", line 158, in <module>
    t.start()
  File "/usr/lib/python2.7/threading.py", line 736, in start
    _start_new_thread(self.__bootstrap, ())
thread.error: can't start new thread
Exception in thread Thread-378:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "./altdns.py", line 115, in get_cname
    progress += 1
TypeError: unsupported operand type(s) for +=: 'NoneType' and 'int'

**Comment by Shad0wSt3p** [comment]
Also have an issue with it being unable to start new threads. Attempted with lightweight (four subdomains) list as well, same issue.

**Comment by infosec-au** [comment]
Hi @merlin303 - this issue has been fixed due to a pull request from @avlidienbrunn. I'm closing this bug report as resolved now.
